# @package suite
defaults:
  - _self_
  - task: xarm_env

suite: dexterous
name: "dexterous"

# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
hidden_dim: 256

# train settings
num_train_steps: 150010
log_every_steps: 1000
save_every_steps: 5000
history: true
history_len: 10

# eval
eval_every_steps: 10
num_eval_episodes: 5
eval_history_len: 10

# data loading
action_after_steps: 1 #8

# obs_keys
pixel_keys: ["pixels"]
proprio_key: "proprioceptive"
feature_key: "features"

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.dexterous.make
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
  height: 128
  width: 128
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  use_egocentric: false
  task_description: "just training"
  pixel_keys: ${suite.pixel_keys}
  eval: ${eval} # eval true mean use robot
  raw_data_path: ${raw_data_path}
  delta_actions: ${delta_actions}
  joint_space_control: ${joint_space_control}
