defaults:
  - _self_
  - agent: baku
  - suite: libero
  - dataloader: libero
  - override hydra/launcher: submitit_local

# wandb
project_name: 'p3po'
run_name: 'open_oven_1028'

# Root Dir
root_dir: /fs/cfar-projects/waypoint_rl/hermes/P3PO
use_p3po: True

# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true
batch_size: 16

# experiment
obs_type: "features" # pixels, features
training_keys: ['graph']
depth_keys: ['depth']
num_demos_per_task: 100
encoder_type: 'resnet' # base, resnet
policy_type: 'gpt' # mlp, gpt
policy_head: deterministic # deterministic, gmm, bet, diffusion, vqbet
use_proprio: false
use_language: false
use_actions: false
prompt: text # text, goal, intermediate_goal
eval: false
eval_only: false
experiment: train
experiment_label: ${policy_head}

raw_data_path: null

# action chunking
temporal_agg: true # aggregate actions over time
# steps_per_obs is 1 or 8
steps_per_obs: 8
num_queries: 8

# expert dataset
expert_dataset: ${dataloader.bc_dataset}

# Load weights
load_bc: false
bc_weight: null

use_wandb: false
point_dimensions: 3
p3po_task_name: "assembly"  
num_tracked_points: 11

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${run_name}_${point_dimensions}d
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
